AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3ECGitHubKMSKeyID:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: KMS Key for GitHub Action Workflow
      Enabled: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  S3ECGitHubKMSKeyIDTestVectors:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: KMS Key for GitHub Action Workflow
      Enabled: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  S3ECGitHubKMSKeyIDAlternate:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: Alternate KMS Key for GitHub Action Workflow
      Enabled: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  S3ECGitHubKMSKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: alias/S3EC-Github-KMS-Key
      TargetKeyId: !Ref S3ECGitHubKMSKeyID

  S3ECGitHubKMSKeyAliasTestVectors:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: alias/S3EC-Github-KMS-Key-TestVectors
      TargetKeyId: !Ref S3ECGitHubKMSKeyIDTestVectors

  S3ECGitHubTestS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: s3ec-github-test-bucket
      LifecycleConfiguration:
        Rules:
          - Id: Expire in 14 days
            Status: Enabled
            ExpirationInDays: 14
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  S3ECGitHubS3BucketPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: S3EC-GitHub-S3-Bucket-Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListBucket'
            Resource:
              - !GetAtt S3ECGitHubTestS3Bucket.Arn
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:DeleteObject'
            Resource:
              - !Join [ "", [ !GetAtt S3ECGitHubTestS3Bucket.Arn, '/*'] ]

  S3ECGitHubTestS3BucketAlternate:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: s3ec-github-test-bucket-alternate
      LifecycleConfiguration:
        Rules:
          - Id: Expire in 14 days
            Status: Enabled
            ExpirationInDays: 14
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  S3ECGitHubS3BucketPolicyAlternate:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: S3EC-GitHub-S3-Bucket-Policy-Alternate
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:DeleteObject'
            Resource:
              - !Join [ "", [ !GetAtt S3ECGitHubTestS3BucketAlternate.Arn, '/*'] ]

  S3ECGitHubTestS3BucketTestVectors:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: s3ec-github-test-bucket-testvectors
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  S3ECGitHubS3BucketPolicyTestVectors:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: S3EC-GitHub-S3-Bucket-Policy-testvectors
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListBucket'
            Resource:
              - !GetAtt S3ECGitHubTestS3BucketTestVectors.Arn
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:DeleteObject'
            Resource:
              - !Join [ "", [ !GetAtt S3ECGitHubTestS3BucketTestVectors.Arn, '/*'] ]

  S3ECGitHubKMSKeyPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Resource": [
                "arn:aws:kms:*:${AWS::AccountId}:key/${S3ECGitHubKMSKeyID}",
                "arn:aws:kms:*:${AWS::AccountId}:${S3ECGitHubKMSKeyAlias}"
              ],
              "Action": [
                "kms:Decrypt",
                "kms:GenerateDataKey",
                "kms:GenerateDataKeyPair"
              ]
            }
          ]
        }
      ManagedPolicyName: S3EC-GitHub-KMS-Key-Policy

  S3ECGitHubKMSKeyPolicyTestVectors:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Resource": [
                "arn:aws:kms:*:${AWS::AccountId}:key/${S3ECGitHubKMSKeyIDTestVectors}",
                "arn:aws:kms:*:${AWS::AccountId}:${S3ECGitHubKMSKeyAliasTestVectors}"
              ],
              "Action": [
                "kms:Decrypt",
                "kms:GenerateDataKey",
                "kms:GenerateDataKeyPair"
              ]
            }
          ]
        }
      ManagedPolicyName: S3EC-GitHub-KMS-Key-Policy-TestVectors

  S3ECGitHubKMSKeyPolicyAlternate:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Resource": [
                "arn:aws:kms:*:${AWS::AccountId}:key/${S3ECGitHubKMSKeyIDAlternate}"
              ],
              "Action": [
                "kms:Decrypt",
                "kms:GenerateDataKey",
                "kms:GenerateDataKeyPair"
              ]
            }
          ]
        }
      ManagedPolicyName: S3EC-GitHub-KMS-Key-Policy-Alternate

  S3ECGithubTestRoleAlternate:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /service-role/
      RoleName: S3EC-GitHub-test-role-alternate
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",   
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": { "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com" },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                  "StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                  },
                  "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:aws/amazon-s3-encryption-client-java:*"
                  }
               }
            },
            {
              "Effect": "Allow",
              "Principal": { "AWS": "arn:aws:iam::${AWS::AccountId}:role/ToolsDevelopment" },
              "Action": "sts:AssumeRole"
            },
            {
              "Effect": "Allow",
              "Principal": { "AWS": "arn:aws:iam::${AWS::AccountId}:role/service-role/S3EC-GitHub-test-role" },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      Description: >-
        Grant GitHub S3 put and get and KMS (alt key) encrypt, decrypt, and generate access
        for testing
      ManagedPolicyArns:
        - !Ref S3ECGitHubKMSKeyPolicyAlternate
        - !Ref S3ECGitHubS3BucketPolicy
        - !Ref S3ECGitHubS3BucketPolicyAlternate

  S3ECGitHubAssumeAlternatePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Resource": [
                "arn:aws:iam::${AWS::AccountId}:role/service-role/${S3ECGithubTestRoleAlternate}"
              ],
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        }
      ManagedPolicyName: S3EC-GitHub-Assume-Alternate-Policy

  S3ECGithubTestRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /service-role/
      RoleName: S3EC-GitHub-test-role
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",   
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": { "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com" },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                  "StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                  },
                  "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:aws/amazon-s3-encryption-client-java:*"
                  }
               }
            },
            {
              "Effect": "Allow",
              "Principal": { "AWS": "arn:aws:iam::${AWS::AccountId}:role/ToolsDevelopment" },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      Description: >-
        Grant GitHub S3 put and get and KMS encrypt, decrypt, and generate access
        for testing
      ManagedPolicyArns:
        - !Ref S3ECGitHubKMSKeyPolicy
        - !Ref S3ECGitHubKMSKeyPolicyTestVectors
        - !Ref S3ECGitHubS3BucketPolicy
        - !Ref S3ECGitHubAssumeAlternatePolicy
        - !Ref S3ECGitHubS3BucketPolicyTestVectors
