name: Continuous Deployment Workflow

on:
  push:
  workflow_dispatch:

env:
  RELEASE_BRANCH: main

jobs:
  Run_CI_Workflow:
    uses: ./.github/workflows/ci-workflow.yml

  #version:
  #  runs-on: ubuntu-latest
  #  permissions:
  #    id-token: write
  #    contents: read
  #
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: codfish/semantic-release-action@v2
  #      with:
  #        branches: $RELEASE_BRANCH
  #        dry_run: true
