name: Continuous Deployment Workflow

on:
  push:
    #branches:
    #    - 'main'

env:
  RELEASE_BRANCH: main

jobs:
  Checkout:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      # TODO: SpotBugs, fmt-maven-plugin
  Run_CI_Workflow:
    needs: Checkout
    uses: ./.github/workflows/ci-workflow.yml

  #version:
  #  runs-on: ubuntu-latest
  #  permissions:
  #    id-token: write
  #    contents: read
  #
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: codfish/semantic-release-action@v2
  #      with:
  #        branches: $RELEASE_BRANCH
  #        dry_run: true
