name: ghi_300.yml
on:
  push:
    branches:
      - tony/refactor-tests
      - '**/ghi-300'

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.CI_AWS_ACCOUNT_ID }}:role/service-role/${{ vars.CI_AWS_ROLE }}
          role-session-name: S3EC-Github-CI-Tests
          aws-region: ${{ vars.CI_AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v3

      # TODO: Add OpenJDK
      # OpenJDK would require a different action than setup-java, so setup is more involved.

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8
          cache: 'maven'

      - name: Compile
        run: |
          mvn --batch-mode -no-transfer-progress clean compile
          mvn --batch-mode -no-transfer-progress test-compile
        shell: bash

      - name: Test
        run: |
          export AWS_S3EC_TEST_BUCKET=${{ vars.CI_S3_BUCKET }}
          export AWS_S3EC_TEST_KMS_KEY_ID=arn:aws:kms:${{ vars.CI_AWS_REGION }}:${{ secrets.CI_AWS_ACCOUNT_ID }}:key/${{ vars.CI_KMS_KEY_ID }}
          export AWS_S3EC_TEST_KMS_KEY_ALIAS=arn:aws:kms:${{ vars.CI_AWS_REGION }}:${{ secrets.CI_AWS_ACCOUNT_ID }}:alias/${{ vars.CI_KMS_KEY_ALIAS }}
          export AWS_REGION=${{ vars.CI_AWS_REGION }}
          mvn -B -ntp -DskipCompile -Dtest=software.amazon.encryption.s3.examples.TestEndOfStreamBehavior test
        shell: bash
