name: Static Analysis

on:
  workflow_call:

jobs:
  SpotBugs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run SpotBugs
        run: mvn -B -ntp com.github.spotbugs:spotbugs-maven-plugin:check
        shell: bash
