name: Static Analysis

on:
  pull_request:
  push:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Run SpotBugs
        run: mvn -T 4 -ntp com.github.spotbugs:spotbugs-maven-plugin:4.7.2.1:spotbugs